/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  BillPaymentTransaction as PrismaBillPaymentTransaction,
} from "@prisma/client";

export class BillPaymentTransactionServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.BillPaymentTransactionCountArgs, "select">
  ): Promise<number> {
    return this.prisma.billPaymentTransaction.count(args);
  }

  async billPaymentTransactions<
    T extends Prisma.BillPaymentTransactionFindManyArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.BillPaymentTransactionFindManyArgs>
  ): Promise<PrismaBillPaymentTransaction[]> {
    return this.prisma.billPaymentTransaction.findMany<Prisma.BillPaymentTransactionFindManyArgs>(
      args
    );
  }
  async billPaymentTransaction<
    T extends Prisma.BillPaymentTransactionFindUniqueArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.BillPaymentTransactionFindUniqueArgs>
  ): Promise<PrismaBillPaymentTransaction | null> {
    return this.prisma.billPaymentTransaction.findUnique(args);
  }
  async createBillPaymentTransaction<
    T extends Prisma.BillPaymentTransactionCreateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.BillPaymentTransactionCreateArgs>
  ): Promise<PrismaBillPaymentTransaction> {
    return this.prisma.billPaymentTransaction.create<T>(args);
  }
  async updateBillPaymentTransaction<
    T extends Prisma.BillPaymentTransactionUpdateArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.BillPaymentTransactionUpdateArgs>
  ): Promise<PrismaBillPaymentTransaction> {
    return this.prisma.billPaymentTransaction.update<T>(args);
  }
  async deleteBillPaymentTransaction<
    T extends Prisma.BillPaymentTransactionDeleteArgs
  >(
    args: Prisma.SelectSubset<T, Prisma.BillPaymentTransactionDeleteArgs>
  ): Promise<PrismaBillPaymentTransaction> {
    return this.prisma.billPaymentTransaction.delete(args);
  }
}
